repos:
    - repo: local
      hooks:
          - id: run-makefile-command
            name: polish
            entry: polish.sh
            language: script
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-json
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: no-commit-to-branch
    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.1
      hooks:
          - id: go-imports
          - id: go-critic
          - id: golangci-lint
          - id: go-fmt
          - id: go-mod-tidy
